// src/app/layout.js

import "./globals.css";

export const metadata = {
  title: "Trikkefestivalen",
  description: "Generated by create next app",
};

// Option 1: use Next.js App Router's viewport export
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
